/**
 * Plan 4c: Parameters subsystem type definitions.
 *
 * A DashboardParameter is a named typed scalar that worksheet SQL can
 * reference via a {{name}} token. Substitution happens before SQLValidator
 * so the validator still sees the final string.
 */

export type ParamType = 'string' | 'number' | 'boolean' | 'date';

/** Scalar payload for a parameter. Dates are ISO-8601 strings. */
export type ParamValue = string | number | boolean;

export type ParamDomainList = { kind: 'list'; values: ParamValue[] };
export type ParamDomainRange = { kind: 'range'; min: number; max: number; step: number };
export type ParamDomainFree = { kind: 'free' };

export type ParamDomain = ParamDomainList | ParamDomainRange | ParamDomainFree;

export type DashboardParameter = {
  /** Stable id, generated by generateZoneId at creation. */
  id: string;
  /** Parameter name — matches /^[A-Za-z_][A-Za-z0-9_]*$/, unique (case-insensitive) within dashboard. */
  name: string;
  type: ParamType;
  value: ParamValue;
  domain: ParamDomain;
  /** ISO-8601 UTC timestamp. */
  createdAt: string;
};

/** Hard cap on a parameter name's length (keeps token regex bounded). */
export const MAX_PARAM_TOKEN_LENGTH = 64;

/**
 * Hard cap on the length of a SQL string post-substitution. Prevents a
 * pathologically long `list` domain value from blowing up a query. The
 * backend enforces the same cap.
 */
export const MAX_SUBSTITUTED_SQL_LEN = 100_000;
