/**
 * Plan 4b: Sets subsystem type definitions.
 *
 * A DashboardSet is a named mutable collection of dimension values stored on
 * a dashboard. Sets are consumed by the ChangeSetAction runtime path and by
 * Filter actions that reference a set via `fieldMapping[i].setRef`.
 */

/** Dedup-safe primitive member type. Strings and numbers only. */
export type SetMember = string | number;

/** Four mutation modes supported by applySetChange. */
export type SetChangeMode = 'add' | 'remove' | 'replace' | 'clear';

export type DashboardSet = {
  /** Stable id, generated by generateZoneId at creation. */
  id: string;
  /** Display name, unique within a dashboard (case-insensitive). */
  name: string;
  /** Dimension column reference. Must match /^[A-Za-z_][A-Za-z0-9_]*$/. */
  dimension: string;
  /** Current members. Deduped, stable-ordered (first-seen wins). */
  members: SetMember[];
  /** ISO-8601 UTC timestamp. */
  createdAt: string;
};

/**
 * Hard cap on set cardinality to keep IN (...) SQL payloads bounded and to
 * protect the JSON persistence path. Replace/add modes truncate at this cap;
 * setOps emits no error — truncation is silent and documented.
 */
export const MAX_SET_MEMBERS = 5000;
