/**
 * GENERATED FILE - do not hand-edit.
 * Regenerate via `npm run proto` (or `bash scripts/regen_proto.sh`).
 * Source: backend/proto/askdb/vizdataservice/v1.proto
 */

// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.1
// source: askdb/vizdataservice/v1.proto

/* eslint-disable */

export const protobufPackage = "askdb.vizdataservice.v1";

/** A.1 DataType */
export enum DataType {
  DATA_TYPE_UNSPECIFIED = 0,
  DATA_TYPE_BOOL = 1,
  /** DATA_TYPE_BOOLEAN - Tableau emits both `bool` and `boolean` */
  DATA_TYPE_BOOLEAN = 2,
  DATA_TYPE_DATE = 3,
  DATA_TYPE_DATE_TIME = 4,
  DATA_TYPE_FLOAT = 5,
  DATA_TYPE_INT = 6,
  DATA_TYPE_NUMBER = 7,
  DATA_TYPE_SPATIAL = 8,
  DATA_TYPE_STRING = 9,
  DATA_TYPE_UNKNOWN = 10,
}

export function dataTypeFromJSON(object: any): DataType {
  switch (object) {
    case 0:
    case "DATA_TYPE_UNSPECIFIED":
      return DataType.DATA_TYPE_UNSPECIFIED;
    case 1:
    case "DATA_TYPE_BOOL":
      return DataType.DATA_TYPE_BOOL;
    case 2:
    case "DATA_TYPE_BOOLEAN":
      return DataType.DATA_TYPE_BOOLEAN;
    case 3:
    case "DATA_TYPE_DATE":
      return DataType.DATA_TYPE_DATE;
    case 4:
    case "DATA_TYPE_DATE_TIME":
      return DataType.DATA_TYPE_DATE_TIME;
    case 5:
    case "DATA_TYPE_FLOAT":
      return DataType.DATA_TYPE_FLOAT;
    case 6:
    case "DATA_TYPE_INT":
      return DataType.DATA_TYPE_INT;
    case 7:
    case "DATA_TYPE_NUMBER":
      return DataType.DATA_TYPE_NUMBER;
    case 8:
    case "DATA_TYPE_SPATIAL":
      return DataType.DATA_TYPE_SPATIAL;
    case 9:
    case "DATA_TYPE_STRING":
      return DataType.DATA_TYPE_STRING;
    case 10:
    case "DATA_TYPE_UNKNOWN":
      return DataType.DATA_TYPE_UNKNOWN;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DataType");
  }
}

export function dataTypeToJSON(object: DataType): string {
  switch (object) {
    case DataType.DATA_TYPE_UNSPECIFIED:
      return "DATA_TYPE_UNSPECIFIED";
    case DataType.DATA_TYPE_BOOL:
      return "DATA_TYPE_BOOL";
    case DataType.DATA_TYPE_BOOLEAN:
      return "DATA_TYPE_BOOLEAN";
    case DataType.DATA_TYPE_DATE:
      return "DATA_TYPE_DATE";
    case DataType.DATA_TYPE_DATE_TIME:
      return "DATA_TYPE_DATE_TIME";
    case DataType.DATA_TYPE_FLOAT:
      return "DATA_TYPE_FLOAT";
    case DataType.DATA_TYPE_INT:
      return "DATA_TYPE_INT";
    case DataType.DATA_TYPE_NUMBER:
      return "DATA_TYPE_NUMBER";
    case DataType.DATA_TYPE_SPATIAL:
      return "DATA_TYPE_SPATIAL";
    case DataType.DATA_TYPE_STRING:
      return "DATA_TYPE_STRING";
    case DataType.DATA_TYPE_UNKNOWN:
      return "DATA_TYPE_UNKNOWN";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DataType");
  }
}

/** A.2 FieldRoleType */
export enum FieldRole {
  FIELD_ROLE_UNSPECIFIED = 0,
  FIELD_ROLE_DIMENSION = 1,
  FIELD_ROLE_MEASURE = 2,
  FIELD_ROLE_UNKNOWN = 3,
}

export function fieldRoleFromJSON(object: any): FieldRole {
  switch (object) {
    case 0:
    case "FIELD_ROLE_UNSPECIFIED":
      return FieldRole.FIELD_ROLE_UNSPECIFIED;
    case 1:
    case "FIELD_ROLE_DIMENSION":
      return FieldRole.FIELD_ROLE_DIMENSION;
    case 2:
    case "FIELD_ROLE_MEASURE":
      return FieldRole.FIELD_ROLE_MEASURE;
    case 3:
    case "FIELD_ROLE_UNKNOWN":
      return FieldRole.FIELD_ROLE_UNKNOWN;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum FieldRole");
  }
}

export function fieldRoleToJSON(object: FieldRole): string {
  switch (object) {
    case FieldRole.FIELD_ROLE_UNSPECIFIED:
      return "FIELD_ROLE_UNSPECIFIED";
    case FieldRole.FIELD_ROLE_DIMENSION:
      return "FIELD_ROLE_DIMENSION";
    case FieldRole.FIELD_ROLE_MEASURE:
      return "FIELD_ROLE_MEASURE";
    case FieldRole.FIELD_ROLE_UNKNOWN:
      return "FIELD_ROLE_UNKNOWN";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum FieldRole");
  }
}

/** A.3 ColumnClass (protobuf) */
export enum ColumnClass {
  COLUMN_CLASS_UNSPECIFIED = 0,
  COLUMN_CLASS_CATEGORICAL_BIN = 1,
  COLUMN_CLASS_DANGLING = 2,
  COLUMN_CLASS_DATABASE = 3,
  COLUMN_CLASS_GROUP = 4,
  COLUMN_CLASS_INSTANCE = 5,
  COLUMN_CLASS_LOCAL_DATA = 6,
  COLUMN_CLASS_MDX_CALC = 7,
  COLUMN_CLASS_METADATA = 8,
  COLUMN_CLASS_NUMERIC_BIN = 9,
  COLUMN_CLASS_USER_CALC = 10,
  COLUMN_CLASS_VISUAL_DATA = 11,
}

export function columnClassFromJSON(object: any): ColumnClass {
  switch (object) {
    case 0:
    case "COLUMN_CLASS_UNSPECIFIED":
      return ColumnClass.COLUMN_CLASS_UNSPECIFIED;
    case 1:
    case "COLUMN_CLASS_CATEGORICAL_BIN":
      return ColumnClass.COLUMN_CLASS_CATEGORICAL_BIN;
    case 2:
    case "COLUMN_CLASS_DANGLING":
      return ColumnClass.COLUMN_CLASS_DANGLING;
    case 3:
    case "COLUMN_CLASS_DATABASE":
      return ColumnClass.COLUMN_CLASS_DATABASE;
    case 4:
    case "COLUMN_CLASS_GROUP":
      return ColumnClass.COLUMN_CLASS_GROUP;
    case 5:
    case "COLUMN_CLASS_INSTANCE":
      return ColumnClass.COLUMN_CLASS_INSTANCE;
    case 6:
    case "COLUMN_CLASS_LOCAL_DATA":
      return ColumnClass.COLUMN_CLASS_LOCAL_DATA;
    case 7:
    case "COLUMN_CLASS_MDX_CALC":
      return ColumnClass.COLUMN_CLASS_MDX_CALC;
    case 8:
    case "COLUMN_CLASS_METADATA":
      return ColumnClass.COLUMN_CLASS_METADATA;
    case 9:
    case "COLUMN_CLASS_NUMERIC_BIN":
      return ColumnClass.COLUMN_CLASS_NUMERIC_BIN;
    case 10:
    case "COLUMN_CLASS_USER_CALC":
      return ColumnClass.COLUMN_CLASS_USER_CALC;
    case 11:
    case "COLUMN_CLASS_VISUAL_DATA":
      return ColumnClass.COLUMN_CLASS_VISUAL_DATA;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum ColumnClass");
  }
}

export function columnClassToJSON(object: ColumnClass): string {
  switch (object) {
    case ColumnClass.COLUMN_CLASS_UNSPECIFIED:
      return "COLUMN_CLASS_UNSPECIFIED";
    case ColumnClass.COLUMN_CLASS_CATEGORICAL_BIN:
      return "COLUMN_CLASS_CATEGORICAL_BIN";
    case ColumnClass.COLUMN_CLASS_DANGLING:
      return "COLUMN_CLASS_DANGLING";
    case ColumnClass.COLUMN_CLASS_DATABASE:
      return "COLUMN_CLASS_DATABASE";
    case ColumnClass.COLUMN_CLASS_GROUP:
      return "COLUMN_CLASS_GROUP";
    case ColumnClass.COLUMN_CLASS_INSTANCE:
      return "COLUMN_CLASS_INSTANCE";
    case ColumnClass.COLUMN_CLASS_LOCAL_DATA:
      return "COLUMN_CLASS_LOCAL_DATA";
    case ColumnClass.COLUMN_CLASS_MDX_CALC:
      return "COLUMN_CLASS_MDX_CALC";
    case ColumnClass.COLUMN_CLASS_METADATA:
      return "COLUMN_CLASS_METADATA";
    case ColumnClass.COLUMN_CLASS_NUMERIC_BIN:
      return "COLUMN_CLASS_NUMERIC_BIN";
    case ColumnClass.COLUMN_CLASS_USER_CALC:
      return "COLUMN_CLASS_USER_CALC";
    case ColumnClass.COLUMN_CLASS_VISUAL_DATA:
      return "COLUMN_CLASS_VISUAL_DATA";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum ColumnClass");
  }
}

/** A.4 MarkType */
export enum MarkType {
  MARK_TYPE_UNSPECIFIED = 0,
  MARK_TYPE_BAR = 1,
  MARK_TYPE_LINE = 2,
  MARK_TYPE_AREA = 3,
  MARK_TYPE_PIE = 4,
  MARK_TYPE_CIRCLE = 5,
  MARK_TYPE_SQUARE = 6,
  MARK_TYPE_TEXT = 7,
  MARK_TYPE_SHAPE = 8,
  MARK_TYPE_MAP = 9,
  MARK_TYPE_POLYGON = 10,
  MARK_TYPE_HEATMAP = 11,
  /** MARK_TYPE_GANTT_BAR - wire string: "gantt-bar" */
  MARK_TYPE_GANTT_BAR = 12,
  /** MARK_TYPE_VIZ_EXTENSION - wire string: "viz-extension" */
  MARK_TYPE_VIZ_EXTENSION = 13,
}

export function markTypeFromJSON(object: any): MarkType {
  switch (object) {
    case 0:
    case "MARK_TYPE_UNSPECIFIED":
      return MarkType.MARK_TYPE_UNSPECIFIED;
    case 1:
    case "MARK_TYPE_BAR":
      return MarkType.MARK_TYPE_BAR;
    case 2:
    case "MARK_TYPE_LINE":
      return MarkType.MARK_TYPE_LINE;
    case 3:
    case "MARK_TYPE_AREA":
      return MarkType.MARK_TYPE_AREA;
    case 4:
    case "MARK_TYPE_PIE":
      return MarkType.MARK_TYPE_PIE;
    case 5:
    case "MARK_TYPE_CIRCLE":
      return MarkType.MARK_TYPE_CIRCLE;
    case 6:
    case "MARK_TYPE_SQUARE":
      return MarkType.MARK_TYPE_SQUARE;
    case 7:
    case "MARK_TYPE_TEXT":
      return MarkType.MARK_TYPE_TEXT;
    case 8:
    case "MARK_TYPE_SHAPE":
      return MarkType.MARK_TYPE_SHAPE;
    case 9:
    case "MARK_TYPE_MAP":
      return MarkType.MARK_TYPE_MAP;
    case 10:
    case "MARK_TYPE_POLYGON":
      return MarkType.MARK_TYPE_POLYGON;
    case 11:
    case "MARK_TYPE_HEATMAP":
      return MarkType.MARK_TYPE_HEATMAP;
    case 12:
    case "MARK_TYPE_GANTT_BAR":
      return MarkType.MARK_TYPE_GANTT_BAR;
    case 13:
    case "MARK_TYPE_VIZ_EXTENSION":
      return MarkType.MARK_TYPE_VIZ_EXTENSION;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum MarkType");
  }
}

export function markTypeToJSON(object: MarkType): string {
  switch (object) {
    case MarkType.MARK_TYPE_UNSPECIFIED:
      return "MARK_TYPE_UNSPECIFIED";
    case MarkType.MARK_TYPE_BAR:
      return "MARK_TYPE_BAR";
    case MarkType.MARK_TYPE_LINE:
      return "MARK_TYPE_LINE";
    case MarkType.MARK_TYPE_AREA:
      return "MARK_TYPE_AREA";
    case MarkType.MARK_TYPE_PIE:
      return "MARK_TYPE_PIE";
    case MarkType.MARK_TYPE_CIRCLE:
      return "MARK_TYPE_CIRCLE";
    case MarkType.MARK_TYPE_SQUARE:
      return "MARK_TYPE_SQUARE";
    case MarkType.MARK_TYPE_TEXT:
      return "MARK_TYPE_TEXT";
    case MarkType.MARK_TYPE_SHAPE:
      return "MARK_TYPE_SHAPE";
    case MarkType.MARK_TYPE_MAP:
      return "MARK_TYPE_MAP";
    case MarkType.MARK_TYPE_POLYGON:
      return "MARK_TYPE_POLYGON";
    case MarkType.MARK_TYPE_HEATMAP:
      return "MARK_TYPE_HEATMAP";
    case MarkType.MARK_TYPE_GANTT_BAR:
      return "MARK_TYPE_GANTT_BAR";
    case MarkType.MARK_TYPE_VIZ_EXTENSION:
      return "MARK_TYPE_VIZ_EXTENSION";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum MarkType");
  }
}

/** A.5 EncodingType */
export enum EncodingType {
  ENCODING_TYPE_UNSPECIFIED = 0,
  ENCODING_TYPE_COLOR = 1,
  ENCODING_TYPE_SIZE = 2,
  ENCODING_TYPE_SHAPE = 3,
  ENCODING_TYPE_LABEL = 4,
  ENCODING_TYPE_TOOLTIP = 5,
  ENCODING_TYPE_DETAIL = 6,
  ENCODING_TYPE_PATH = 7,
  ENCODING_TYPE_ANGLE = 8,
  ENCODING_TYPE_GEOMETRY = 9,
  ENCODING_TYPE_CUSTOM = 10,
}

export function encodingTypeFromJSON(object: any): EncodingType {
  switch (object) {
    case 0:
    case "ENCODING_TYPE_UNSPECIFIED":
      return EncodingType.ENCODING_TYPE_UNSPECIFIED;
    case 1:
    case "ENCODING_TYPE_COLOR":
      return EncodingType.ENCODING_TYPE_COLOR;
    case 2:
    case "ENCODING_TYPE_SIZE":
      return EncodingType.ENCODING_TYPE_SIZE;
    case 3:
    case "ENCODING_TYPE_SHAPE":
      return EncodingType.ENCODING_TYPE_SHAPE;
    case 4:
    case "ENCODING_TYPE_LABEL":
      return EncodingType.ENCODING_TYPE_LABEL;
    case 5:
    case "ENCODING_TYPE_TOOLTIP":
      return EncodingType.ENCODING_TYPE_TOOLTIP;
    case 6:
    case "ENCODING_TYPE_DETAIL":
      return EncodingType.ENCODING_TYPE_DETAIL;
    case 7:
    case "ENCODING_TYPE_PATH":
      return EncodingType.ENCODING_TYPE_PATH;
    case 8:
    case "ENCODING_TYPE_ANGLE":
      return EncodingType.ENCODING_TYPE_ANGLE;
    case 9:
    case "ENCODING_TYPE_GEOMETRY":
      return EncodingType.ENCODING_TYPE_GEOMETRY;
    case 10:
    case "ENCODING_TYPE_CUSTOM":
      return EncodingType.ENCODING_TYPE_CUSTOM;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum EncodingType");
  }
}

export function encodingTypeToJSON(object: EncodingType): string {
  switch (object) {
    case EncodingType.ENCODING_TYPE_UNSPECIFIED:
      return "ENCODING_TYPE_UNSPECIFIED";
    case EncodingType.ENCODING_TYPE_COLOR:
      return "ENCODING_TYPE_COLOR";
    case EncodingType.ENCODING_TYPE_SIZE:
      return "ENCODING_TYPE_SIZE";
    case EncodingType.ENCODING_TYPE_SHAPE:
      return "ENCODING_TYPE_SHAPE";
    case EncodingType.ENCODING_TYPE_LABEL:
      return "ENCODING_TYPE_LABEL";
    case EncodingType.ENCODING_TYPE_TOOLTIP:
      return "ENCODING_TYPE_TOOLTIP";
    case EncodingType.ENCODING_TYPE_DETAIL:
      return "ENCODING_TYPE_DETAIL";
    case EncodingType.ENCODING_TYPE_PATH:
      return "ENCODING_TYPE_PATH";
    case EncodingType.ENCODING_TYPE_ANGLE:
      return "ENCODING_TYPE_ANGLE";
    case EncodingType.ENCODING_TYPE_GEOMETRY:
      return "ENCODING_TYPE_GEOMETRY";
    case EncodingType.ENCODING_TYPE_CUSTOM:
      return "ENCODING_TYPE_CUSTOM";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum EncodingType");
  }
}

/**
 * ShelfKind from the Plan 7a brief (roadmap Plan 7a deliverable 1).
 * ROW/COLUMN are worksheet pill shelves; the marks-card channels mirror
 * EncodingType but are addressed on the shelf axis (Part III.1 + III.2).
 */
export enum ShelfKind {
  SHELF_KIND_UNSPECIFIED = 0,
  SHELF_KIND_ROW = 1,
  SHELF_KIND_COLUMN = 2,
  SHELF_KIND_DETAIL = 3,
  SHELF_KIND_COLOR = 4,
  SHELF_KIND_SIZE = 5,
  SHELF_KIND_SHAPE = 6,
  SHELF_KIND_LABEL = 7,
  SHELF_KIND_PATH = 8,
  SHELF_KIND_ANGLE = 9,
  SHELF_KIND_TOOLTIP = 10,
  SHELF_KIND_PAGES = 11,
  SHELF_KIND_FILTER = 12,
}

export function shelfKindFromJSON(object: any): ShelfKind {
  switch (object) {
    case 0:
    case "SHELF_KIND_UNSPECIFIED":
      return ShelfKind.SHELF_KIND_UNSPECIFIED;
    case 1:
    case "SHELF_KIND_ROW":
      return ShelfKind.SHELF_KIND_ROW;
    case 2:
    case "SHELF_KIND_COLUMN":
      return ShelfKind.SHELF_KIND_COLUMN;
    case 3:
    case "SHELF_KIND_DETAIL":
      return ShelfKind.SHELF_KIND_DETAIL;
    case 4:
    case "SHELF_KIND_COLOR":
      return ShelfKind.SHELF_KIND_COLOR;
    case 5:
    case "SHELF_KIND_SIZE":
      return ShelfKind.SHELF_KIND_SIZE;
    case 6:
    case "SHELF_KIND_SHAPE":
      return ShelfKind.SHELF_KIND_SHAPE;
    case 7:
    case "SHELF_KIND_LABEL":
      return ShelfKind.SHELF_KIND_LABEL;
    case 8:
    case "SHELF_KIND_PATH":
      return ShelfKind.SHELF_KIND_PATH;
    case 9:
    case "SHELF_KIND_ANGLE":
      return ShelfKind.SHELF_KIND_ANGLE;
    case 10:
    case "SHELF_KIND_TOOLTIP":
      return ShelfKind.SHELF_KIND_TOOLTIP;
    case 11:
    case "SHELF_KIND_PAGES":
      return ShelfKind.SHELF_KIND_PAGES;
    case 12:
    case "SHELF_KIND_FILTER":
      return ShelfKind.SHELF_KIND_FILTER;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum ShelfKind");
  }
}

export function shelfKindToJSON(object: ShelfKind): string {
  switch (object) {
    case ShelfKind.SHELF_KIND_UNSPECIFIED:
      return "SHELF_KIND_UNSPECIFIED";
    case ShelfKind.SHELF_KIND_ROW:
      return "SHELF_KIND_ROW";
    case ShelfKind.SHELF_KIND_COLUMN:
      return "SHELF_KIND_COLUMN";
    case ShelfKind.SHELF_KIND_DETAIL:
      return "SHELF_KIND_DETAIL";
    case ShelfKind.SHELF_KIND_COLOR:
      return "SHELF_KIND_COLOR";
    case ShelfKind.SHELF_KIND_SIZE:
      return "SHELF_KIND_SIZE";
    case ShelfKind.SHELF_KIND_SHAPE:
      return "SHELF_KIND_SHAPE";
    case ShelfKind.SHELF_KIND_LABEL:
      return "SHELF_KIND_LABEL";
    case ShelfKind.SHELF_KIND_PATH:
      return "SHELF_KIND_PATH";
    case ShelfKind.SHELF_KIND_ANGLE:
      return "SHELF_KIND_ANGLE";
    case ShelfKind.SHELF_KIND_TOOLTIP:
      return "SHELF_KIND_TOOLTIP";
    case ShelfKind.SHELF_KIND_PAGES:
      return "SHELF_KIND_PAGES";
    case ShelfKind.SHELF_KIND_FILTER:
      return "SHELF_KIND_FILTER";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum ShelfKind");
  }
}

/** A.8 FilterType - 4 kinds, discriminator for FilterSpec. */
export enum FilterKind {
  FILTER_KIND_UNSPECIFIED = 0,
  /** FILTER_KIND_CATEGORICAL - wire string: "categorical" */
  FILTER_KIND_CATEGORICAL = 1,
  /** FILTER_KIND_HIERARCHICAL - wire string: "hierarchical" */
  FILTER_KIND_HIERARCHICAL = 2,
  /** FILTER_KIND_RANGE - wire string: "range" */
  FILTER_KIND_RANGE = 3,
  /** FILTER_KIND_RELATIVE_DATE - wire string: "relativeDate" */
  FILTER_KIND_RELATIVE_DATE = 4,
}

export function filterKindFromJSON(object: any): FilterKind {
  switch (object) {
    case 0:
    case "FILTER_KIND_UNSPECIFIED":
      return FilterKind.FILTER_KIND_UNSPECIFIED;
    case 1:
    case "FILTER_KIND_CATEGORICAL":
      return FilterKind.FILTER_KIND_CATEGORICAL;
    case 2:
    case "FILTER_KIND_HIERARCHICAL":
      return FilterKind.FILTER_KIND_HIERARCHICAL;
    case 3:
    case "FILTER_KIND_RANGE":
      return FilterKind.FILTER_KIND_RANGE;
    case 4:
    case "FILTER_KIND_RELATIVE_DATE":
      return FilterKind.FILTER_KIND_RELATIVE_DATE;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum FilterKind");
  }
}

export function filterKindToJSON(object: FilterKind): string {
  switch (object) {
    case FilterKind.FILTER_KIND_UNSPECIFIED:
      return "FILTER_KIND_UNSPECIFIED";
    case FilterKind.FILTER_KIND_CATEGORICAL:
      return "FILTER_KIND_CATEGORICAL";
    case FilterKind.FILTER_KIND_HIERARCHICAL:
      return "FILTER_KIND_HIERARCHICAL";
    case FilterKind.FILTER_KIND_RANGE:
      return "FILTER_KIND_RANGE";
    case FilterKind.FILTER_KIND_RELATIVE_DATE:
      return "FILTER_KIND_RELATIVE_DATE";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum FilterKind");
  }
}

/** A.14 AggregationType - superset union of Appendix A.14. */
export enum AggType {
  AGG_TYPE_UNSPECIFIED = 0,
  AGG_TYPE_SUM = 1,
  AGG_TYPE_AVG = 2,
  AGG_TYPE_COUNT = 3,
  AGG_TYPE_COUNTD = 4,
  AGG_TYPE_MIN = 5,
  AGG_TYPE_MAX = 6,
  AGG_TYPE_MEDIAN = 7,
  AGG_TYPE_VAR = 8,
  AGG_TYPE_VARP = 9,
  AGG_TYPE_STDEV = 10,
  AGG_TYPE_STDEVP = 11,
  AGG_TYPE_KURTOSIS = 12,
  AGG_TYPE_SKEWNESS = 13,
  AGG_TYPE_ATTR = 14,
  AGG_TYPE_NONE = 15,
  AGG_TYPE_PERCENTILE = 16,
  AGG_TYPE_COLLECT = 17,
  AGG_TYPE_IN_OUT = 18,
  AGG_TYPE_END = 19,
  AGG_TYPE_QUART1 = 20,
  AGG_TYPE_QUART3 = 21,
  AGG_TYPE_USER = 22,
  /** AGG_TYPE_YEAR - Date truncations (A.14 continuation) */
  AGG_TYPE_YEAR = 30,
  AGG_TYPE_QTR = 31,
  AGG_TYPE_MONTH = 32,
  AGG_TYPE_WEEK = 33,
  AGG_TYPE_DAY = 34,
  AGG_TYPE_HOUR = 35,
  AGG_TYPE_MINUTE = 36,
  AGG_TYPE_SECOND = 37,
  AGG_TYPE_WEEKDAY = 38,
  AGG_TYPE_MONTH_YEAR = 39,
  AGG_TYPE_MDY = 40,
  AGG_TYPE_TRUNC_YEAR = 41,
  AGG_TYPE_TRUNC_QTR = 42,
  AGG_TYPE_TRUNC_MONTH = 43,
  AGG_TYPE_TRUNC_WEEK = 44,
  AGG_TYPE_TRUNC_DAY = 45,
  AGG_TYPE_TRUNC_HOUR = 46,
  AGG_TYPE_TRUNC_MINUTE = 47,
  AGG_TYPE_TRUNC_SECOND = 48,
}

export function aggTypeFromJSON(object: any): AggType {
  switch (object) {
    case 0:
    case "AGG_TYPE_UNSPECIFIED":
      return AggType.AGG_TYPE_UNSPECIFIED;
    case 1:
    case "AGG_TYPE_SUM":
      return AggType.AGG_TYPE_SUM;
    case 2:
    case "AGG_TYPE_AVG":
      return AggType.AGG_TYPE_AVG;
    case 3:
    case "AGG_TYPE_COUNT":
      return AggType.AGG_TYPE_COUNT;
    case 4:
    case "AGG_TYPE_COUNTD":
      return AggType.AGG_TYPE_COUNTD;
    case 5:
    case "AGG_TYPE_MIN":
      return AggType.AGG_TYPE_MIN;
    case 6:
    case "AGG_TYPE_MAX":
      return AggType.AGG_TYPE_MAX;
    case 7:
    case "AGG_TYPE_MEDIAN":
      return AggType.AGG_TYPE_MEDIAN;
    case 8:
    case "AGG_TYPE_VAR":
      return AggType.AGG_TYPE_VAR;
    case 9:
    case "AGG_TYPE_VARP":
      return AggType.AGG_TYPE_VARP;
    case 10:
    case "AGG_TYPE_STDEV":
      return AggType.AGG_TYPE_STDEV;
    case 11:
    case "AGG_TYPE_STDEVP":
      return AggType.AGG_TYPE_STDEVP;
    case 12:
    case "AGG_TYPE_KURTOSIS":
      return AggType.AGG_TYPE_KURTOSIS;
    case 13:
    case "AGG_TYPE_SKEWNESS":
      return AggType.AGG_TYPE_SKEWNESS;
    case 14:
    case "AGG_TYPE_ATTR":
      return AggType.AGG_TYPE_ATTR;
    case 15:
    case "AGG_TYPE_NONE":
      return AggType.AGG_TYPE_NONE;
    case 16:
    case "AGG_TYPE_PERCENTILE":
      return AggType.AGG_TYPE_PERCENTILE;
    case 17:
    case "AGG_TYPE_COLLECT":
      return AggType.AGG_TYPE_COLLECT;
    case 18:
    case "AGG_TYPE_IN_OUT":
      return AggType.AGG_TYPE_IN_OUT;
    case 19:
    case "AGG_TYPE_END":
      return AggType.AGG_TYPE_END;
    case 20:
    case "AGG_TYPE_QUART1":
      return AggType.AGG_TYPE_QUART1;
    case 21:
    case "AGG_TYPE_QUART3":
      return AggType.AGG_TYPE_QUART3;
    case 22:
    case "AGG_TYPE_USER":
      return AggType.AGG_TYPE_USER;
    case 30:
    case "AGG_TYPE_YEAR":
      return AggType.AGG_TYPE_YEAR;
    case 31:
    case "AGG_TYPE_QTR":
      return AggType.AGG_TYPE_QTR;
    case 32:
    case "AGG_TYPE_MONTH":
      return AggType.AGG_TYPE_MONTH;
    case 33:
    case "AGG_TYPE_WEEK":
      return AggType.AGG_TYPE_WEEK;
    case 34:
    case "AGG_TYPE_DAY":
      return AggType.AGG_TYPE_DAY;
    case 35:
    case "AGG_TYPE_HOUR":
      return AggType.AGG_TYPE_HOUR;
    case 36:
    case "AGG_TYPE_MINUTE":
      return AggType.AGG_TYPE_MINUTE;
    case 37:
    case "AGG_TYPE_SECOND":
      return AggType.AGG_TYPE_SECOND;
    case 38:
    case "AGG_TYPE_WEEKDAY":
      return AggType.AGG_TYPE_WEEKDAY;
    case 39:
    case "AGG_TYPE_MONTH_YEAR":
      return AggType.AGG_TYPE_MONTH_YEAR;
    case 40:
    case "AGG_TYPE_MDY":
      return AggType.AGG_TYPE_MDY;
    case 41:
    case "AGG_TYPE_TRUNC_YEAR":
      return AggType.AGG_TYPE_TRUNC_YEAR;
    case 42:
    case "AGG_TYPE_TRUNC_QTR":
      return AggType.AGG_TYPE_TRUNC_QTR;
    case 43:
    case "AGG_TYPE_TRUNC_MONTH":
      return AggType.AGG_TYPE_TRUNC_MONTH;
    case 44:
    case "AGG_TYPE_TRUNC_WEEK":
      return AggType.AGG_TYPE_TRUNC_WEEK;
    case 45:
    case "AGG_TYPE_TRUNC_DAY":
      return AggType.AGG_TYPE_TRUNC_DAY;
    case 46:
    case "AGG_TYPE_TRUNC_HOUR":
      return AggType.AGG_TYPE_TRUNC_HOUR;
    case 47:
    case "AGG_TYPE_TRUNC_MINUTE":
      return AggType.AGG_TYPE_TRUNC_MINUTE;
    case 48:
    case "AGG_TYPE_TRUNC_SECOND":
      return AggType.AGG_TYPE_TRUNC_SECOND;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum AggType");
  }
}

export function aggTypeToJSON(object: AggType): string {
  switch (object) {
    case AggType.AGG_TYPE_UNSPECIFIED:
      return "AGG_TYPE_UNSPECIFIED";
    case AggType.AGG_TYPE_SUM:
      return "AGG_TYPE_SUM";
    case AggType.AGG_TYPE_AVG:
      return "AGG_TYPE_AVG";
    case AggType.AGG_TYPE_COUNT:
      return "AGG_TYPE_COUNT";
    case AggType.AGG_TYPE_COUNTD:
      return "AGG_TYPE_COUNTD";
    case AggType.AGG_TYPE_MIN:
      return "AGG_TYPE_MIN";
    case AggType.AGG_TYPE_MAX:
      return "AGG_TYPE_MAX";
    case AggType.AGG_TYPE_MEDIAN:
      return "AGG_TYPE_MEDIAN";
    case AggType.AGG_TYPE_VAR:
      return "AGG_TYPE_VAR";
    case AggType.AGG_TYPE_VARP:
      return "AGG_TYPE_VARP";
    case AggType.AGG_TYPE_STDEV:
      return "AGG_TYPE_STDEV";
    case AggType.AGG_TYPE_STDEVP:
      return "AGG_TYPE_STDEVP";
    case AggType.AGG_TYPE_KURTOSIS:
      return "AGG_TYPE_KURTOSIS";
    case AggType.AGG_TYPE_SKEWNESS:
      return "AGG_TYPE_SKEWNESS";
    case AggType.AGG_TYPE_ATTR:
      return "AGG_TYPE_ATTR";
    case AggType.AGG_TYPE_NONE:
      return "AGG_TYPE_NONE";
    case AggType.AGG_TYPE_PERCENTILE:
      return "AGG_TYPE_PERCENTILE";
    case AggType.AGG_TYPE_COLLECT:
      return "AGG_TYPE_COLLECT";
    case AggType.AGG_TYPE_IN_OUT:
      return "AGG_TYPE_IN_OUT";
    case AggType.AGG_TYPE_END:
      return "AGG_TYPE_END";
    case AggType.AGG_TYPE_QUART1:
      return "AGG_TYPE_QUART1";
    case AggType.AGG_TYPE_QUART3:
      return "AGG_TYPE_QUART3";
    case AggType.AGG_TYPE_USER:
      return "AGG_TYPE_USER";
    case AggType.AGG_TYPE_YEAR:
      return "AGG_TYPE_YEAR";
    case AggType.AGG_TYPE_QTR:
      return "AGG_TYPE_QTR";
    case AggType.AGG_TYPE_MONTH:
      return "AGG_TYPE_MONTH";
    case AggType.AGG_TYPE_WEEK:
      return "AGG_TYPE_WEEK";
    case AggType.AGG_TYPE_DAY:
      return "AGG_TYPE_DAY";
    case AggType.AGG_TYPE_HOUR:
      return "AGG_TYPE_HOUR";
    case AggType.AGG_TYPE_MINUTE:
      return "AGG_TYPE_MINUTE";
    case AggType.AGG_TYPE_SECOND:
      return "AGG_TYPE_SECOND";
    case AggType.AGG_TYPE_WEEKDAY:
      return "AGG_TYPE_WEEKDAY";
    case AggType.AGG_TYPE_MONTH_YEAR:
      return "AGG_TYPE_MONTH_YEAR";
    case AggType.AGG_TYPE_MDY:
      return "AGG_TYPE_MDY";
    case AggType.AGG_TYPE_TRUNC_YEAR:
      return "AGG_TYPE_TRUNC_YEAR";
    case AggType.AGG_TYPE_TRUNC_QTR:
      return "AGG_TYPE_TRUNC_QTR";
    case AggType.AGG_TYPE_TRUNC_MONTH:
      return "AGG_TYPE_TRUNC_MONTH";
    case AggType.AGG_TYPE_TRUNC_WEEK:
      return "AGG_TYPE_TRUNC_WEEK";
    case AggType.AGG_TYPE_TRUNC_DAY:
      return "AGG_TYPE_TRUNC_DAY";
    case AggType.AGG_TYPE_TRUNC_HOUR:
      return "AGG_TYPE_TRUNC_HOUR";
    case AggType.AGG_TYPE_TRUNC_MINUTE:
      return "AGG_TYPE_TRUNC_MINUTE";
    case AggType.AGG_TYPE_TRUNC_SECOND:
      return "AGG_TYPE_TRUNC_SECOND";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum AggType");
  }
}

/**
 * Field reference. `id` is the stable column identifier.
 * `semantic_role` is optional (e.g. "[Geographical].[Latitude]").
 * `is_disagg=true` disables default aggregation (Build_Tableau VIII.2).
 */
export interface Field {
  id: string;
  dataType: DataType;
  role: FieldRole;
  semanticRole: string;
  aggregation: AggType;
  isDisagg: boolean;
  columnClass: ColumnClass;
}

/** Calculation - formula string + is_adhoc flag. Parser lands in Plan 8a. */
export interface Calculation {
  id: string;
  formula: string;
  isAdhoc: boolean;
}

/** Shelf - ordered list of Field refs on a given channel. */
export interface Shelf {
  kind: ShelfKind;
  fields: Field[];
}

/**
 * Encoding - marks-card binding with optional custom_encoding_type_id
 * escape hatch (Build_Tableau III.2 - drives Viz Extensions).
 */
export interface Encoding {
  fieldEncodingId: string;
  encodingType: EncodingType;
  customEncodingTypeId: string;
  field?: Field | undefined;
}

export interface CategoricalFilterProps {
  values: string[];
  isExcludeMode: boolean;
  caseSensitive: boolean;
}

export interface HierarchicalFilterProps {
  filterLevels: string[];
  hierValSelectionModels: string[];
}

export interface RangeFilterProps {
  min: number;
  max: number;
  /** Null-handling: "keep" | "drop" | "only". */
  rangeNullOption: string;
}

export interface RelativeDateFilterProps {
  /** ISO-8601; empty = "now at query time" */
  anchorDate: string;
  /** "years"|"quarters"|"months"|"weeks"|"days"|"hours"|"minutes" */
  periodType: string;
  /** "last"|"next"|"current"|"toDate" */
  dateRangeType: string;
  rangeN: number;
}

export interface FilterSpec {
  filterKind: FilterKind;
  field?:
    | Field
    | undefined;
  /** Exactly one of these is populated based on filter_kind. */
  categorical?: CategoricalFilterProps | undefined;
  hierarchical?: HierarchicalFilterProps | undefined;
  range?: RangeFilterProps | undefined;
  relativeDate?: RelativeDateFilterProps | undefined;
  hasNull: boolean;
  includeNull: boolean;
  isLogicalTableScopedFilter: boolean;
  /**
   * Placement in the 9-stage filter pipeline (Build_Tableau IV.7).
   * "extract"|"datasource"|"context"|"dimension"|"measure"
   * |"table_calc"|"totals". LOD stages live on LodCalculation.
   */
  filterStage: string;
  filterProperties: { [key: string]: string };
}

export interface FilterSpec_FilterPropertiesEntry {
  key: string;
  value: string;
}

/**
 * Workbook-scoped parameter (Build_Tableau VI). Domain kinds:
 * "list" | "range" | "free".
 */
export interface Parameter {
  id: string;
  name: string;
  dataType: DataType;
  value: string;
  domainKind: string;
  domainValues: string[];
  domainMin: number;
  domainMax: number;
  domainStep: number;
}

/** LOD calculation (Build_Tableau V.2). lod_kind: "fixed"|"include"|"exclude". */
export interface LodCalculation {
  id: string;
  lodKind: string;
  lodDims: Field[];
  innerCalculation?: Calculation | undefined;
  outerAggregation: AggType;
}

/**
 * Plan 8c §V.1/§V.3 — table calculation spec. Per-viz list lives at
 * VisualSpec.table_calc_specs (field 16). Server-side (RUNNING_*, WINDOW_*,
 * RANK_*, INDEX, FIRST, LAST, SIZE, TOTAL, PCT_TOTAL) lower to LogicalOpOver
 * at compile time. Client-side (LOOKUP, PREVIOUS_VALUE, DIFF, IS_DISTINCT,
 * IS_STACKED) flow through to the frontend evaluator post-fetch.
 */
export interface TableCalcSpec {
  calcId: string;
  /** canonical Tableau spelling */
  function: string;
  argField: string;
  addressing: string[];
  partitioning: string[];
  /** "across" | "down" | "table" | "pane" | "pane_down" | "specific" */
  direction: string;
  /** "" | "asc" | "desc" */
  sort: string;
  /** 0 if unset (LOOKUP/DIFF/PREVIOUS_VALUE/PERCENTILE) */
  offset: number;
  /** discriminates legitimate 0 from unset */
  hasOffset: boolean;
}

/**
 * Analytics pane slots (Build_Tableau XIII). Plan 9a introduces typed
 * repeated fields for reference-lines / bands / distributions / totals;
 * legacy `slots` remains for forward-compat with any generic entry.
 */
export interface Analytics {
  slots: Analytics_Slot[];
  referenceLines: ReferenceLineSpec[];
  referenceBands: ReferenceBandSpec[];
  distributions: ReferenceDistributionSpec[];
  totals: TotalsSpec[];
  boxPlots: BoxPlotSpec[];
}

export interface Analytics_Slot {
  id: string;
  kind: string;
  properties: { [key: string]: string };
}

export interface Analytics_Slot_PropertiesEntry {
  key: string;
  value: string;
}

/**
 * Plan 9e — Tableau §XIII.1 box plot. Composes via ReferenceDistributionSpec
 * (5 aggregated rows: q1 / median / q3 + whisker_low / whisker_high). Whisker
 * method picks the whisker computation (Tukey 1.5*IQR / min-max / percentile).
 */
export interface BoxPlotSpec {
  /** "x" | "y" */
  axis: string;
  /** "tukey" | "min-max" | "percentile" */
  whiskerMethod: string;
  /** 1..49  when whisker_method=="percentile"; else 0 */
  whiskerPercentileLo: number;
  /** 51..99 when whisker_method=="percentile"; else 0 */
  whiskerPercentileHi: number;
  /** discriminates legitimate (0,0) unset from bad tuple */
  hasWhiskerPercentile: boolean;
  showOutliers: boolean;
  /** "#RRGGBB" */
  fillColor: string;
  /** 0..1 */
  fillOpacity: number;
  /** "entire" | "pane" | "cell" */
  scope: string;
}

/**
 * Build_Tableau XIII.1 + Appendix C tabdocaxis!ReferenceLineSpecification.
 * Scope maps to Tableau Scope: "entire" = full data, "pane" = per-pane
 * group, "cell" = per-cell (window).
 */
export interface ReferenceLineSpec {
  /** "x" | "y" */
  axis: string;
  /** "constant"|"mean"|"median"|"sum"|"min"|"max"|"percentile" */
  aggregation: string;
  /** used when aggregation=="constant"; else ignored */
  value: number;
  /** discriminates legitimate 0 constant from unset */
  hasValue: boolean;
  /** 1..99; used when aggregation=="percentile" */
  percentile: number;
  /** "entire" | "pane" | "cell" */
  scope: string;
  /** "value" | "computation" | "custom" | "none" */
  label: string;
  customLabel: string;
  /** "solid" | "dashed" | "dotted" */
  lineStyle: string;
  /** "#RRGGBB" */
  color: string;
  showMarker: boolean;
}

export interface ReferenceBandSpec {
  axis: string;
  fromSpec?: ReferenceLineSpec | undefined;
  toSpec?:
    | ReferenceLineSpec
    | undefined;
  /** "#RRGGBB" */
  fill: string;
  /** 0..1 */
  fillOpacity: number;
}

export interface ReferenceDistributionSpec {
  axis: string;
  /** ordered */
  percentiles: number[];
  /** "entire" | "pane" | "cell" */
  scope: string;
  /** "confidence" | "quantile" | "stddev" */
  style: string;
  color: string;
}

/**
 * Per Build_Tableau IV.7 step 9, totals are issued as SEPARATE queries.
 * `should_affect_totals` mirrors Tableau's Filter::ShouldAffectTotals
 * flag at the totals-spec level (individual filters still carry their
 * own placement via FilterSpec.filter_stage).
 */
export interface TotalsSpec {
  /** "grand_total" | "subtotal" | "both" */
  kind: string;
  /** "row" | "column" | "both" */
  axis: string;
  /** Appendix A.14 AggType spelling */
  aggregation: string;
  /** "before" | "after" */
  position: string;
  /** true = honor normal filters; false = skip */
  shouldAffectTotals: boolean;
}

/** VisualSpec - the canonical IR. */
export interface VisualSpec {
  sheetId: string;
  fields: Field[];
  shelves: Shelf[];
  encodings: Encoding[];
  filters: FilterSpec[];
  parameters: Parameter[];
  lodCalculations: LodCalculation[];
  markType: MarkType;
  analytics?:
    | Analytics
    | undefined;
  /** AI-origin marker (Build_Tableau I.5). */
  isGenerativeAiWebAuthoring: boolean;
  /**
   * Snowflake vs separate cross-product (Build_Tableau IV.3).
   * "snowflake" | "separate". Default "separate".
   */
  domainType: string;
  /**
   * Plan 8b §V.2 — per-viz LOD placement overrides. Each entry is a
   * LodCalculation.id whose compiled partition_by was hand-edited in the
   * .twb XML; auto-placement in `place_lod_in_order` skips these so the
   * user's manual choice is preserved.
   */
  joinLodOverrides: string[];
  /**
   * Plan 8c §V.1/§V.3 — per-viz table-calc specs attached to this viz.
   * Resolution split per spec.function:
   *   server-side (RUNNING_*, WINDOW_*, RANK_*, INDEX, FIRST, LAST, SIZE,
   *                TOTAL, PCT_TOTAL): lowered to LogicalOpOver by
   *                table_calc.compile_table_calc.
   *   client-side (LOOKUP, PREVIOUS_VALUE, DIFF, IS_DISTINCT, IS_STACKED):
   *                forwarded to frontend evaluator post-fetch.
   */
  tableCalcSpecs: TableCalcSpec[];
}

function createBaseField(): Field {
  return { id: "", dataType: 0, role: 0, semanticRole: "", aggregation: 0, isDisagg: false, columnClass: 0 };
}

export const Field: MessageFns<Field> = {
  fromJSON(object: any): Field {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      dataType: isSet(object.dataType)
        ? dataTypeFromJSON(object.dataType)
        : isSet(object.data_type)
        ? dataTypeFromJSON(object.data_type)
        : 0,
      role: isSet(object.role) ? fieldRoleFromJSON(object.role) : 0,
      semanticRole: isSet(object.semanticRole)
        ? globalThis.String(object.semanticRole)
        : isSet(object.semantic_role)
        ? globalThis.String(object.semantic_role)
        : "",
      aggregation: isSet(object.aggregation) ? aggTypeFromJSON(object.aggregation) : 0,
      isDisagg: isSet(object.isDisagg)
        ? globalThis.Boolean(object.isDisagg)
        : isSet(object.is_disagg)
        ? globalThis.Boolean(object.is_disagg)
        : false,
      columnClass: isSet(object.columnClass)
        ? columnClassFromJSON(object.columnClass)
        : isSet(object.column_class)
        ? columnClassFromJSON(object.column_class)
        : 0,
    };
  },

  toJSON(message: Field): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.dataType !== 0) {
      obj.dataType = dataTypeToJSON(message.dataType);
    }
    if (message.role !== 0) {
      obj.role = fieldRoleToJSON(message.role);
    }
    if (message.semanticRole !== "") {
      obj.semanticRole = message.semanticRole;
    }
    if (message.aggregation !== 0) {
      obj.aggregation = aggTypeToJSON(message.aggregation);
    }
    if (message.isDisagg !== false) {
      obj.isDisagg = message.isDisagg;
    }
    if (message.columnClass !== 0) {
      obj.columnClass = columnClassToJSON(message.columnClass);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Field>, I>>(base?: I): Field {
    return Field.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Field>, I>>(object: I): Field {
    const message = createBaseField();
    message.id = object.id ?? "";
    message.dataType = object.dataType ?? 0;
    message.role = object.role ?? 0;
    message.semanticRole = object.semanticRole ?? "";
    message.aggregation = object.aggregation ?? 0;
    message.isDisagg = object.isDisagg ?? false;
    message.columnClass = object.columnClass ?? 0;
    return message;
  },
};

function createBaseCalculation(): Calculation {
  return { id: "", formula: "", isAdhoc: false };
}

export const Calculation: MessageFns<Calculation> = {
  fromJSON(object: any): Calculation {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      formula: isSet(object.formula) ? globalThis.String(object.formula) : "",
      isAdhoc: isSet(object.isAdhoc)
        ? globalThis.Boolean(object.isAdhoc)
        : isSet(object.is_adhoc)
        ? globalThis.Boolean(object.is_adhoc)
        : false,
    };
  },

  toJSON(message: Calculation): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.formula !== "") {
      obj.formula = message.formula;
    }
    if (message.isAdhoc !== false) {
      obj.isAdhoc = message.isAdhoc;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Calculation>, I>>(base?: I): Calculation {
    return Calculation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Calculation>, I>>(object: I): Calculation {
    const message = createBaseCalculation();
    message.id = object.id ?? "";
    message.formula = object.formula ?? "";
    message.isAdhoc = object.isAdhoc ?? false;
    return message;
  },
};

function createBaseShelf(): Shelf {
  return { kind: 0, fields: [] };
}

export const Shelf: MessageFns<Shelf> = {
  fromJSON(object: any): Shelf {
    return {
      kind: isSet(object.kind) ? shelfKindFromJSON(object.kind) : 0,
      fields: globalThis.Array.isArray(object?.fields) ? object.fields.map((e: any) => Field.fromJSON(e)) : [],
    };
  },

  toJSON(message: Shelf): unknown {
    const obj: any = {};
    if (message.kind !== 0) {
      obj.kind = shelfKindToJSON(message.kind);
    }
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => Field.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Shelf>, I>>(base?: I): Shelf {
    return Shelf.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Shelf>, I>>(object: I): Shelf {
    const message = createBaseShelf();
    message.kind = object.kind ?? 0;
    message.fields = object.fields?.map((e) => Field.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEncoding(): Encoding {
  return { fieldEncodingId: "", encodingType: 0, customEncodingTypeId: "", field: undefined };
}

export const Encoding: MessageFns<Encoding> = {
  fromJSON(object: any): Encoding {
    return {
      fieldEncodingId: isSet(object.fieldEncodingId)
        ? globalThis.String(object.fieldEncodingId)
        : isSet(object.field_encoding_id)
        ? globalThis.String(object.field_encoding_id)
        : "",
      encodingType: isSet(object.encodingType)
        ? encodingTypeFromJSON(object.encodingType)
        : isSet(object.encoding_type)
        ? encodingTypeFromJSON(object.encoding_type)
        : 0,
      customEncodingTypeId: isSet(object.customEncodingTypeId)
        ? globalThis.String(object.customEncodingTypeId)
        : isSet(object.custom_encoding_type_id)
        ? globalThis.String(object.custom_encoding_type_id)
        : "",
      field: isSet(object.field) ? Field.fromJSON(object.field) : undefined,
    };
  },

  toJSON(message: Encoding): unknown {
    const obj: any = {};
    if (message.fieldEncodingId !== "") {
      obj.fieldEncodingId = message.fieldEncodingId;
    }
    if (message.encodingType !== 0) {
      obj.encodingType = encodingTypeToJSON(message.encodingType);
    }
    if (message.customEncodingTypeId !== "") {
      obj.customEncodingTypeId = message.customEncodingTypeId;
    }
    if (message.field !== undefined) {
      obj.field = Field.toJSON(message.field);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Encoding>, I>>(base?: I): Encoding {
    return Encoding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Encoding>, I>>(object: I): Encoding {
    const message = createBaseEncoding();
    message.fieldEncodingId = object.fieldEncodingId ?? "";
    message.encodingType = object.encodingType ?? 0;
    message.customEncodingTypeId = object.customEncodingTypeId ?? "";
    message.field = (object.field !== undefined && object.field !== null) ? Field.fromPartial(object.field) : undefined;
    return message;
  },
};

function createBaseCategoricalFilterProps(): CategoricalFilterProps {
  return { values: [], isExcludeMode: false, caseSensitive: false };
}

export const CategoricalFilterProps: MessageFns<CategoricalFilterProps> = {
  fromJSON(object: any): CategoricalFilterProps {
    return {
      values: globalThis.Array.isArray(object?.values)
        ? object.values.map((e: any) => globalThis.String(e))
        : [],
      isExcludeMode: isSet(object.isExcludeMode)
        ? globalThis.Boolean(object.isExcludeMode)
        : isSet(object.is_exclude_mode)
        ? globalThis.Boolean(object.is_exclude_mode)
        : false,
      caseSensitive: isSet(object.caseSensitive)
        ? globalThis.Boolean(object.caseSensitive)
        : isSet(object.case_sensitive)
        ? globalThis.Boolean(object.case_sensitive)
        : false,
    };
  },

  toJSON(message: CategoricalFilterProps): unknown {
    const obj: any = {};
    if (message.values?.length) {
      obj.values = message.values;
    }
    if (message.isExcludeMode !== false) {
      obj.isExcludeMode = message.isExcludeMode;
    }
    if (message.caseSensitive !== false) {
      obj.caseSensitive = message.caseSensitive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CategoricalFilterProps>, I>>(base?: I): CategoricalFilterProps {
    return CategoricalFilterProps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CategoricalFilterProps>, I>>(object: I): CategoricalFilterProps {
    const message = createBaseCategoricalFilterProps();
    message.values = object.values?.map((e) => e) || [];
    message.isExcludeMode = object.isExcludeMode ?? false;
    message.caseSensitive = object.caseSensitive ?? false;
    return message;
  },
};

function createBaseHierarchicalFilterProps(): HierarchicalFilterProps {
  return { filterLevels: [], hierValSelectionModels: [] };
}

export const HierarchicalFilterProps: MessageFns<HierarchicalFilterProps> = {
  fromJSON(object: any): HierarchicalFilterProps {
    return {
      filterLevels: globalThis.Array.isArray(object?.filterLevels)
        ? object.filterLevels.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.filter_levels)
        ? object.filter_levels.map((e: any) =>
          globalThis.String(e)
        )
        : [],
      hierValSelectionModels: globalThis.Array.isArray(object?.hierValSelectionModels)
        ? object.hierValSelectionModels.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.hier_val_selection_models)
        ? object.hier_val_selection_models.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: HierarchicalFilterProps): unknown {
    const obj: any = {};
    if (message.filterLevels?.length) {
      obj.filterLevels = message.filterLevels;
    }
    if (message.hierValSelectionModels?.length) {
      obj.hierValSelectionModels = message.hierValSelectionModels;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HierarchicalFilterProps>, I>>(base?: I): HierarchicalFilterProps {
    return HierarchicalFilterProps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HierarchicalFilterProps>, I>>(object: I): HierarchicalFilterProps {
    const message = createBaseHierarchicalFilterProps();
    message.filterLevels = object.filterLevels?.map((e) => e) || [];
    message.hierValSelectionModels = object.hierValSelectionModels?.map((e) => e) || [];
    return message;
  },
};

function createBaseRangeFilterProps(): RangeFilterProps {
  return { min: 0, max: 0, rangeNullOption: "" };
}

export const RangeFilterProps: MessageFns<RangeFilterProps> = {
  fromJSON(object: any): RangeFilterProps {
    return {
      min: isSet(object.min) ? globalThis.Number(object.min) : 0,
      max: isSet(object.max) ? globalThis.Number(object.max) : 0,
      rangeNullOption: isSet(object.rangeNullOption)
        ? globalThis.String(object.rangeNullOption)
        : isSet(object.range_null_option)
        ? globalThis.String(object.range_null_option)
        : "",
    };
  },

  toJSON(message: RangeFilterProps): unknown {
    const obj: any = {};
    if (message.min !== 0) {
      obj.min = message.min;
    }
    if (message.max !== 0) {
      obj.max = message.max;
    }
    if (message.rangeNullOption !== "") {
      obj.rangeNullOption = message.rangeNullOption;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RangeFilterProps>, I>>(base?: I): RangeFilterProps {
    return RangeFilterProps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RangeFilterProps>, I>>(object: I): RangeFilterProps {
    const message = createBaseRangeFilterProps();
    message.min = object.min ?? 0;
    message.max = object.max ?? 0;
    message.rangeNullOption = object.rangeNullOption ?? "";
    return message;
  },
};

function createBaseRelativeDateFilterProps(): RelativeDateFilterProps {
  return { anchorDate: "", periodType: "", dateRangeType: "", rangeN: 0 };
}

export const RelativeDateFilterProps: MessageFns<RelativeDateFilterProps> = {
  fromJSON(object: any): RelativeDateFilterProps {
    return {
      anchorDate: isSet(object.anchorDate)
        ? globalThis.String(object.anchorDate)
        : isSet(object.anchor_date)
        ? globalThis.String(object.anchor_date)
        : "",
      periodType: isSet(object.periodType)
        ? globalThis.String(object.periodType)
        : isSet(object.period_type)
        ? globalThis.String(object.period_type)
        : "",
      dateRangeType: isSet(object.dateRangeType)
        ? globalThis.String(object.dateRangeType)
        : isSet(object.date_range_type)
        ? globalThis.String(object.date_range_type)
        : "",
      rangeN: isSet(object.rangeN)
        ? globalThis.Number(object.rangeN)
        : isSet(object.range_n)
        ? globalThis.Number(object.range_n)
        : 0,
    };
  },

  toJSON(message: RelativeDateFilterProps): unknown {
    const obj: any = {};
    if (message.anchorDate !== "") {
      obj.anchorDate = message.anchorDate;
    }
    if (message.periodType !== "") {
      obj.periodType = message.periodType;
    }
    if (message.dateRangeType !== "") {
      obj.dateRangeType = message.dateRangeType;
    }
    if (message.rangeN !== 0) {
      obj.rangeN = Math.round(message.rangeN);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelativeDateFilterProps>, I>>(base?: I): RelativeDateFilterProps {
    return RelativeDateFilterProps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelativeDateFilterProps>, I>>(object: I): RelativeDateFilterProps {
    const message = createBaseRelativeDateFilterProps();
    message.anchorDate = object.anchorDate ?? "";
    message.periodType = object.periodType ?? "";
    message.dateRangeType = object.dateRangeType ?? "";
    message.rangeN = object.rangeN ?? 0;
    return message;
  },
};

function createBaseFilterSpec(): FilterSpec {
  return {
    filterKind: 0,
    field: undefined,
    categorical: undefined,
    hierarchical: undefined,
    range: undefined,
    relativeDate: undefined,
    hasNull: false,
    includeNull: false,
    isLogicalTableScopedFilter: false,
    filterStage: "",
    filterProperties: {},
  };
}

export const FilterSpec: MessageFns<FilterSpec> = {
  fromJSON(object: any): FilterSpec {
    return {
      filterKind: isSet(object.filterKind)
        ? filterKindFromJSON(object.filterKind)
        : isSet(object.filter_kind)
        ? filterKindFromJSON(object.filter_kind)
        : 0,
      field: isSet(object.field) ? Field.fromJSON(object.field) : undefined,
      categorical: isSet(object.categorical) ? CategoricalFilterProps.fromJSON(object.categorical) : undefined,
      hierarchical: isSet(object.hierarchical) ? HierarchicalFilterProps.fromJSON(object.hierarchical) : undefined,
      range: isSet(object.range) ? RangeFilterProps.fromJSON(object.range) : undefined,
      relativeDate: isSet(object.relativeDate)
        ? RelativeDateFilterProps.fromJSON(object.relativeDate)
        : isSet(object.relative_date)
        ? RelativeDateFilterProps.fromJSON(object.relative_date)
        : undefined,
      hasNull: isSet(object.hasNull)
        ? globalThis.Boolean(object.hasNull)
        : isSet(object.has_null)
        ? globalThis.Boolean(object.has_null)
        : false,
      includeNull: isSet(object.includeNull)
        ? globalThis.Boolean(object.includeNull)
        : isSet(object.include_null)
        ? globalThis.Boolean(object.include_null)
        : false,
      isLogicalTableScopedFilter: isSet(object.isLogicalTableScopedFilter)
        ? globalThis.Boolean(object.isLogicalTableScopedFilter)
        : isSet(object.is_logical_table_scoped_filter)
        ? globalThis.Boolean(object.is_logical_table_scoped_filter)
        : false,
      filterStage: isSet(object.filterStage)
        ? globalThis.String(object.filterStage)
        : isSet(object.filter_stage)
        ? globalThis.String(object.filter_stage)
        : "",
      filterProperties: isObject(object.filterProperties)
        ? (globalThis.Object.entries(object.filterProperties) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.filter_properties)
        ? (globalThis.Object.entries(object.filter_properties) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: FilterSpec): unknown {
    const obj: any = {};
    if (message.filterKind !== 0) {
      obj.filterKind = filterKindToJSON(message.filterKind);
    }
    if (message.field !== undefined) {
      obj.field = Field.toJSON(message.field);
    }
    if (message.categorical !== undefined) {
      obj.categorical = CategoricalFilterProps.toJSON(message.categorical);
    }
    if (message.hierarchical !== undefined) {
      obj.hierarchical = HierarchicalFilterProps.toJSON(message.hierarchical);
    }
    if (message.range !== undefined) {
      obj.range = RangeFilterProps.toJSON(message.range);
    }
    if (message.relativeDate !== undefined) {
      obj.relativeDate = RelativeDateFilterProps.toJSON(message.relativeDate);
    }
    if (message.hasNull !== false) {
      obj.hasNull = message.hasNull;
    }
    if (message.includeNull !== false) {
      obj.includeNull = message.includeNull;
    }
    if (message.isLogicalTableScopedFilter !== false) {
      obj.isLogicalTableScopedFilter = message.isLogicalTableScopedFilter;
    }
    if (message.filterStage !== "") {
      obj.filterStage = message.filterStage;
    }
    if (message.filterProperties) {
      const entries = globalThis.Object.entries(message.filterProperties) as [string, string][];
      if (entries.length > 0) {
        obj.filterProperties = {};
        entries.forEach(([k, v]) => {
          obj.filterProperties[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FilterSpec>, I>>(base?: I): FilterSpec {
    return FilterSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FilterSpec>, I>>(object: I): FilterSpec {
    const message = createBaseFilterSpec();
    message.filterKind = object.filterKind ?? 0;
    message.field = (object.field !== undefined && object.field !== null) ? Field.fromPartial(object.field) : undefined;
    message.categorical = (object.categorical !== undefined && object.categorical !== null)
      ? CategoricalFilterProps.fromPartial(object.categorical)
      : undefined;
    message.hierarchical = (object.hierarchical !== undefined && object.hierarchical !== null)
      ? HierarchicalFilterProps.fromPartial(object.hierarchical)
      : undefined;
    message.range = (object.range !== undefined && object.range !== null)
      ? RangeFilterProps.fromPartial(object.range)
      : undefined;
    message.relativeDate = (object.relativeDate !== undefined && object.relativeDate !== null)
      ? RelativeDateFilterProps.fromPartial(object.relativeDate)
      : undefined;
    message.hasNull = object.hasNull ?? false;
    message.includeNull = object.includeNull ?? false;
    message.isLogicalTableScopedFilter = object.isLogicalTableScopedFilter ?? false;
    message.filterStage = object.filterStage ?? "";
    message.filterProperties = (globalThis.Object.entries(object.filterProperties ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseFilterSpec_FilterPropertiesEntry(): FilterSpec_FilterPropertiesEntry {
  return { key: "", value: "" };
}

export const FilterSpec_FilterPropertiesEntry: MessageFns<FilterSpec_FilterPropertiesEntry> = {
  fromJSON(object: any): FilterSpec_FilterPropertiesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: FilterSpec_FilterPropertiesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FilterSpec_FilterPropertiesEntry>, I>>(
    base?: I,
  ): FilterSpec_FilterPropertiesEntry {
    return FilterSpec_FilterPropertiesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FilterSpec_FilterPropertiesEntry>, I>>(
    object: I,
  ): FilterSpec_FilterPropertiesEntry {
    const message = createBaseFilterSpec_FilterPropertiesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseParameter(): Parameter {
  return {
    id: "",
    name: "",
    dataType: 0,
    value: "",
    domainKind: "",
    domainValues: [],
    domainMin: 0,
    domainMax: 0,
    domainStep: 0,
  };
}

export const Parameter: MessageFns<Parameter> = {
  fromJSON(object: any): Parameter {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      dataType: isSet(object.dataType)
        ? dataTypeFromJSON(object.dataType)
        : isSet(object.data_type)
        ? dataTypeFromJSON(object.data_type)
        : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      domainKind: isSet(object.domainKind)
        ? globalThis.String(object.domainKind)
        : isSet(object.domain_kind)
        ? globalThis.String(object.domain_kind)
        : "",
      domainValues: globalThis.Array.isArray(object?.domainValues)
        ? object.domainValues.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.domain_values)
        ? object.domain_values.map((e: any) => globalThis.String(e))
        : [],
      domainMin: isSet(object.domainMin)
        ? globalThis.Number(object.domainMin)
        : isSet(object.domain_min)
        ? globalThis.Number(object.domain_min)
        : 0,
      domainMax: isSet(object.domainMax)
        ? globalThis.Number(object.domainMax)
        : isSet(object.domain_max)
        ? globalThis.Number(object.domain_max)
        : 0,
      domainStep: isSet(object.domainStep)
        ? globalThis.Number(object.domainStep)
        : isSet(object.domain_step)
        ? globalThis.Number(object.domain_step)
        : 0,
    };
  },

  toJSON(message: Parameter): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.dataType !== 0) {
      obj.dataType = dataTypeToJSON(message.dataType);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.domainKind !== "") {
      obj.domainKind = message.domainKind;
    }
    if (message.domainValues?.length) {
      obj.domainValues = message.domainValues;
    }
    if (message.domainMin !== 0) {
      obj.domainMin = message.domainMin;
    }
    if (message.domainMax !== 0) {
      obj.domainMax = message.domainMax;
    }
    if (message.domainStep !== 0) {
      obj.domainStep = message.domainStep;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Parameter>, I>>(base?: I): Parameter {
    return Parameter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Parameter>, I>>(object: I): Parameter {
    const message = createBaseParameter();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.dataType = object.dataType ?? 0;
    message.value = object.value ?? "";
    message.domainKind = object.domainKind ?? "";
    message.domainValues = object.domainValues?.map((e) => e) || [];
    message.domainMin = object.domainMin ?? 0;
    message.domainMax = object.domainMax ?? 0;
    message.domainStep = object.domainStep ?? 0;
    return message;
  },
};

function createBaseLodCalculation(): LodCalculation {
  return { id: "", lodKind: "", lodDims: [], innerCalculation: undefined, outerAggregation: 0 };
}

export const LodCalculation: MessageFns<LodCalculation> = {
  fromJSON(object: any): LodCalculation {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      lodKind: isSet(object.lodKind)
        ? globalThis.String(object.lodKind)
        : isSet(object.lod_kind)
        ? globalThis.String(object.lod_kind)
        : "",
      lodDims: globalThis.Array.isArray(object?.lodDims)
        ? object.lodDims.map((e: any) => Field.fromJSON(e))
        : globalThis.Array.isArray(object?.lod_dims)
        ? object.lod_dims.map((e: any) => Field.fromJSON(e))
        : [],
      innerCalculation: isSet(object.innerCalculation)
        ? Calculation.fromJSON(object.innerCalculation)
        : isSet(object.inner_calculation)
        ? Calculation.fromJSON(object.inner_calculation)
        : undefined,
      outerAggregation: isSet(object.outerAggregation)
        ? aggTypeFromJSON(object.outerAggregation)
        : isSet(object.outer_aggregation)
        ? aggTypeFromJSON(object.outer_aggregation)
        : 0,
    };
  },

  toJSON(message: LodCalculation): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.lodKind !== "") {
      obj.lodKind = message.lodKind;
    }
    if (message.lodDims?.length) {
      obj.lodDims = message.lodDims.map((e) => Field.toJSON(e));
    }
    if (message.innerCalculation !== undefined) {
      obj.innerCalculation = Calculation.toJSON(message.innerCalculation);
    }
    if (message.outerAggregation !== 0) {
      obj.outerAggregation = aggTypeToJSON(message.outerAggregation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LodCalculation>, I>>(base?: I): LodCalculation {
    return LodCalculation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LodCalculation>, I>>(object: I): LodCalculation {
    const message = createBaseLodCalculation();
    message.id = object.id ?? "";
    message.lodKind = object.lodKind ?? "";
    message.lodDims = object.lodDims?.map((e) => Field.fromPartial(e)) || [];
    message.innerCalculation = (object.innerCalculation !== undefined && object.innerCalculation !== null)
      ? Calculation.fromPartial(object.innerCalculation)
      : undefined;
    message.outerAggregation = object.outerAggregation ?? 0;
    return message;
  },
};

function createBaseTableCalcSpec(): TableCalcSpec {
  return {
    calcId: "",
    function: "",
    argField: "",
    addressing: [],
    partitioning: [],
    direction: "",
    sort: "",
    offset: 0,
    hasOffset: false,
  };
}

export const TableCalcSpec: MessageFns<TableCalcSpec> = {
  fromJSON(object: any): TableCalcSpec {
    return {
      calcId: isSet(object.calcId)
        ? globalThis.String(object.calcId)
        : isSet(object.calc_id)
        ? globalThis.String(object.calc_id)
        : "",
      function: isSet(object.function) ? globalThis.String(object.function) : "",
      argField: isSet(object.argField)
        ? globalThis.String(object.argField)
        : isSet(object.arg_field)
        ? globalThis.String(object.arg_field)
        : "",
      addressing: globalThis.Array.isArray(object?.addressing)
        ? object.addressing.map((e: any) => globalThis.String(e))
        : [],
      partitioning: globalThis.Array.isArray(object?.partitioning)
        ? object.partitioning.map((e: any) => globalThis.String(e))
        : [],
      direction: isSet(object.direction) ? globalThis.String(object.direction) : "",
      sort: isSet(object.sort) ? globalThis.String(object.sort) : "",
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      hasOffset: isSet(object.hasOffset)
        ? globalThis.Boolean(object.hasOffset)
        : isSet(object.has_offset)
        ? globalThis.Boolean(object.has_offset)
        : false,
    };
  },

  toJSON(message: TableCalcSpec): unknown {
    const obj: any = {};
    if (message.calcId !== "") {
      obj.calcId = message.calcId;
    }
    if (message.function !== "") {
      obj.function = message.function;
    }
    if (message.argField !== "") {
      obj.argField = message.argField;
    }
    if (message.addressing?.length) {
      obj.addressing = message.addressing;
    }
    if (message.partitioning?.length) {
      obj.partitioning = message.partitioning;
    }
    if (message.direction !== "") {
      obj.direction = message.direction;
    }
    if (message.sort !== "") {
      obj.sort = message.sort;
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.hasOffset !== false) {
      obj.hasOffset = message.hasOffset;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TableCalcSpec>, I>>(base?: I): TableCalcSpec {
    return TableCalcSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TableCalcSpec>, I>>(object: I): TableCalcSpec {
    const message = createBaseTableCalcSpec();
    message.calcId = object.calcId ?? "";
    message.function = object.function ?? "";
    message.argField = object.argField ?? "";
    message.addressing = object.addressing?.map((e) => e) || [];
    message.partitioning = object.partitioning?.map((e) => e) || [];
    message.direction = object.direction ?? "";
    message.sort = object.sort ?? "";
    message.offset = object.offset ?? 0;
    message.hasOffset = object.hasOffset ?? false;
    return message;
  },
};

function createBaseAnalytics(): Analytics {
  return { slots: [], referenceLines: [], referenceBands: [], distributions: [], totals: [], boxPlots: [] };
}

export const Analytics: MessageFns<Analytics> = {
  fromJSON(object: any): Analytics {
    return {
      slots: globalThis.Array.isArray(object?.slots) ? object.slots.map((e: any) => Analytics_Slot.fromJSON(e)) : [],
      referenceLines: globalThis.Array.isArray(object?.referenceLines)
        ? object.referenceLines.map((e: any) => ReferenceLineSpec.fromJSON(e))
        : globalThis.Array.isArray(object?.reference_lines)
        ? object.reference_lines.map((e: any) => ReferenceLineSpec.fromJSON(e))
        : [],
      referenceBands: globalThis.Array.isArray(object?.referenceBands)
        ? object.referenceBands.map((e: any) => ReferenceBandSpec.fromJSON(e))
        : globalThis.Array.isArray(object?.reference_bands)
        ? object.reference_bands.map((e: any) => ReferenceBandSpec.fromJSON(e))
        : [],
      distributions: globalThis.Array.isArray(object?.distributions)
        ? object.distributions.map((e: any) => ReferenceDistributionSpec.fromJSON(e))
        : [],
      totals: globalThis.Array.isArray(object?.totals) ? object.totals.map((e: any) => TotalsSpec.fromJSON(e)) : [],
      boxPlots: globalThis.Array.isArray(object?.boxPlots)
        ? object.boxPlots.map((e: any) => BoxPlotSpec.fromJSON(e))
        : globalThis.Array.isArray(object?.box_plots)
        ? object.box_plots.map((e: any) => BoxPlotSpec.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Analytics): unknown {
    const obj: any = {};
    if (message.slots?.length) {
      obj.slots = message.slots.map((e) => Analytics_Slot.toJSON(e));
    }
    if (message.referenceLines?.length) {
      obj.referenceLines = message.referenceLines.map((e) => ReferenceLineSpec.toJSON(e));
    }
    if (message.referenceBands?.length) {
      obj.referenceBands = message.referenceBands.map((e) => ReferenceBandSpec.toJSON(e));
    }
    if (message.distributions?.length) {
      obj.distributions = message.distributions.map((e) => ReferenceDistributionSpec.toJSON(e));
    }
    if (message.totals?.length) {
      obj.totals = message.totals.map((e) => TotalsSpec.toJSON(e));
    }
    if (message.boxPlots?.length) {
      obj.boxPlots = message.boxPlots.map((e) => BoxPlotSpec.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Analytics>, I>>(base?: I): Analytics {
    return Analytics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Analytics>, I>>(object: I): Analytics {
    const message = createBaseAnalytics();
    message.slots = object.slots?.map((e) => Analytics_Slot.fromPartial(e)) || [];
    message.referenceLines = object.referenceLines?.map((e) => ReferenceLineSpec.fromPartial(e)) || [];
    message.referenceBands = object.referenceBands?.map((e) => ReferenceBandSpec.fromPartial(e)) || [];
    message.distributions = object.distributions?.map((e) => ReferenceDistributionSpec.fromPartial(e)) || [];
    message.totals = object.totals?.map((e) => TotalsSpec.fromPartial(e)) || [];
    message.boxPlots = object.boxPlots?.map((e) => BoxPlotSpec.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAnalytics_Slot(): Analytics_Slot {
  return { id: "", kind: "", properties: {} };
}

export const Analytics_Slot: MessageFns<Analytics_Slot> = {
  fromJSON(object: any): Analytics_Slot {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      properties: isObject(object.properties)
        ? (globalThis.Object.entries(object.properties) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: Analytics_Slot): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.properties) {
      const entries = globalThis.Object.entries(message.properties) as [string, string][];
      if (entries.length > 0) {
        obj.properties = {};
        entries.forEach(([k, v]) => {
          obj.properties[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Analytics_Slot>, I>>(base?: I): Analytics_Slot {
    return Analytics_Slot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Analytics_Slot>, I>>(object: I): Analytics_Slot {
    const message = createBaseAnalytics_Slot();
    message.id = object.id ?? "";
    message.kind = object.kind ?? "";
    message.properties = (globalThis.Object.entries(object.properties ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseAnalytics_Slot_PropertiesEntry(): Analytics_Slot_PropertiesEntry {
  return { key: "", value: "" };
}

export const Analytics_Slot_PropertiesEntry: MessageFns<Analytics_Slot_PropertiesEntry> = {
  fromJSON(object: any): Analytics_Slot_PropertiesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Analytics_Slot_PropertiesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Analytics_Slot_PropertiesEntry>, I>>(base?: I): Analytics_Slot_PropertiesEntry {
    return Analytics_Slot_PropertiesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Analytics_Slot_PropertiesEntry>, I>>(
    object: I,
  ): Analytics_Slot_PropertiesEntry {
    const message = createBaseAnalytics_Slot_PropertiesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseBoxPlotSpec(): BoxPlotSpec {
  return {
    axis: "",
    whiskerMethod: "",
    whiskerPercentileLo: 0,
    whiskerPercentileHi: 0,
    hasWhiskerPercentile: false,
    showOutliers: false,
    fillColor: "",
    fillOpacity: 0,
    scope: "",
  };
}

export const BoxPlotSpec: MessageFns<BoxPlotSpec> = {
  fromJSON(object: any): BoxPlotSpec {
    return {
      axis: isSet(object.axis) ? globalThis.String(object.axis) : "",
      whiskerMethod: isSet(object.whiskerMethod)
        ? globalThis.String(object.whiskerMethod)
        : isSet(object.whisker_method)
        ? globalThis.String(object.whisker_method)
        : "",
      whiskerPercentileLo: isSet(object.whiskerPercentileLo)
        ? globalThis.Number(object.whiskerPercentileLo)
        : isSet(object.whisker_percentile_lo)
        ? globalThis.Number(object.whisker_percentile_lo)
        : 0,
      whiskerPercentileHi: isSet(object.whiskerPercentileHi)
        ? globalThis.Number(object.whiskerPercentileHi)
        : isSet(object.whisker_percentile_hi)
        ? globalThis.Number(object.whisker_percentile_hi)
        : 0,
      hasWhiskerPercentile: isSet(object.hasWhiskerPercentile)
        ? globalThis.Boolean(object.hasWhiskerPercentile)
        : isSet(object.has_whisker_percentile)
        ? globalThis.Boolean(object.has_whisker_percentile)
        : false,
      showOutliers: isSet(object.showOutliers)
        ? globalThis.Boolean(object.showOutliers)
        : isSet(object.show_outliers)
        ? globalThis.Boolean(object.show_outliers)
        : false,
      fillColor: isSet(object.fillColor)
        ? globalThis.String(object.fillColor)
        : isSet(object.fill_color)
        ? globalThis.String(object.fill_color)
        : "",
      fillOpacity: isSet(object.fillOpacity)
        ? globalThis.Number(object.fillOpacity)
        : isSet(object.fill_opacity)
        ? globalThis.Number(object.fill_opacity)
        : 0,
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
    };
  },

  toJSON(message: BoxPlotSpec): unknown {
    const obj: any = {};
    if (message.axis !== "") {
      obj.axis = message.axis;
    }
    if (message.whiskerMethod !== "") {
      obj.whiskerMethod = message.whiskerMethod;
    }
    if (message.whiskerPercentileLo !== 0) {
      obj.whiskerPercentileLo = Math.round(message.whiskerPercentileLo);
    }
    if (message.whiskerPercentileHi !== 0) {
      obj.whiskerPercentileHi = Math.round(message.whiskerPercentileHi);
    }
    if (message.hasWhiskerPercentile !== false) {
      obj.hasWhiskerPercentile = message.hasWhiskerPercentile;
    }
    if (message.showOutliers !== false) {
      obj.showOutliers = message.showOutliers;
    }
    if (message.fillColor !== "") {
      obj.fillColor = message.fillColor;
    }
    if (message.fillOpacity !== 0) {
      obj.fillOpacity = message.fillOpacity;
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoxPlotSpec>, I>>(base?: I): BoxPlotSpec {
    return BoxPlotSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoxPlotSpec>, I>>(object: I): BoxPlotSpec {
    const message = createBaseBoxPlotSpec();
    message.axis = object.axis ?? "";
    message.whiskerMethod = object.whiskerMethod ?? "";
    message.whiskerPercentileLo = object.whiskerPercentileLo ?? 0;
    message.whiskerPercentileHi = object.whiskerPercentileHi ?? 0;
    message.hasWhiskerPercentile = object.hasWhiskerPercentile ?? false;
    message.showOutliers = object.showOutliers ?? false;
    message.fillColor = object.fillColor ?? "";
    message.fillOpacity = object.fillOpacity ?? 0;
    message.scope = object.scope ?? "";
    return message;
  },
};

function createBaseReferenceLineSpec(): ReferenceLineSpec {
  return {
    axis: "",
    aggregation: "",
    value: 0,
    hasValue: false,
    percentile: 0,
    scope: "",
    label: "",
    customLabel: "",
    lineStyle: "",
    color: "",
    showMarker: false,
  };
}

export const ReferenceLineSpec: MessageFns<ReferenceLineSpec> = {
  fromJSON(object: any): ReferenceLineSpec {
    return {
      axis: isSet(object.axis) ? globalThis.String(object.axis) : "",
      aggregation: isSet(object.aggregation) ? globalThis.String(object.aggregation) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      hasValue: isSet(object.hasValue)
        ? globalThis.Boolean(object.hasValue)
        : isSet(object.has_value)
        ? globalThis.Boolean(object.has_value)
        : false,
      percentile: isSet(object.percentile) ? globalThis.Number(object.percentile) : 0,
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      customLabel: isSet(object.customLabel)
        ? globalThis.String(object.customLabel)
        : isSet(object.custom_label)
        ? globalThis.String(object.custom_label)
        : "",
      lineStyle: isSet(object.lineStyle)
        ? globalThis.String(object.lineStyle)
        : isSet(object.line_style)
        ? globalThis.String(object.line_style)
        : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
      showMarker: isSet(object.showMarker)
        ? globalThis.Boolean(object.showMarker)
        : isSet(object.show_marker)
        ? globalThis.Boolean(object.show_marker)
        : false,
    };
  },

  toJSON(message: ReferenceLineSpec): unknown {
    const obj: any = {};
    if (message.axis !== "") {
      obj.axis = message.axis;
    }
    if (message.aggregation !== "") {
      obj.aggregation = message.aggregation;
    }
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (message.hasValue !== false) {
      obj.hasValue = message.hasValue;
    }
    if (message.percentile !== 0) {
      obj.percentile = Math.round(message.percentile);
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.customLabel !== "") {
      obj.customLabel = message.customLabel;
    }
    if (message.lineStyle !== "") {
      obj.lineStyle = message.lineStyle;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    if (message.showMarker !== false) {
      obj.showMarker = message.showMarker;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReferenceLineSpec>, I>>(base?: I): ReferenceLineSpec {
    return ReferenceLineSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReferenceLineSpec>, I>>(object: I): ReferenceLineSpec {
    const message = createBaseReferenceLineSpec();
    message.axis = object.axis ?? "";
    message.aggregation = object.aggregation ?? "";
    message.value = object.value ?? 0;
    message.hasValue = object.hasValue ?? false;
    message.percentile = object.percentile ?? 0;
    message.scope = object.scope ?? "";
    message.label = object.label ?? "";
    message.customLabel = object.customLabel ?? "";
    message.lineStyle = object.lineStyle ?? "";
    message.color = object.color ?? "";
    message.showMarker = object.showMarker ?? false;
    return message;
  },
};

function createBaseReferenceBandSpec(): ReferenceBandSpec {
  return { axis: "", fromSpec: undefined, toSpec: undefined, fill: "", fillOpacity: 0 };
}

export const ReferenceBandSpec: MessageFns<ReferenceBandSpec> = {
  fromJSON(object: any): ReferenceBandSpec {
    return {
      axis: isSet(object.axis) ? globalThis.String(object.axis) : "",
      fromSpec: isSet(object.fromSpec)
        ? ReferenceLineSpec.fromJSON(object.fromSpec)
        : isSet(object.from_spec)
        ? ReferenceLineSpec.fromJSON(object.from_spec)
        : undefined,
      toSpec: isSet(object.toSpec)
        ? ReferenceLineSpec.fromJSON(object.toSpec)
        : isSet(object.to_spec)
        ? ReferenceLineSpec.fromJSON(object.to_spec)
        : undefined,
      fill: isSet(object.fill) ? globalThis.String(object.fill) : "",
      fillOpacity: isSet(object.fillOpacity)
        ? globalThis.Number(object.fillOpacity)
        : isSet(object.fill_opacity)
        ? globalThis.Number(object.fill_opacity)
        : 0,
    };
  },

  toJSON(message: ReferenceBandSpec): unknown {
    const obj: any = {};
    if (message.axis !== "") {
      obj.axis = message.axis;
    }
    if (message.fromSpec !== undefined) {
      obj.fromSpec = ReferenceLineSpec.toJSON(message.fromSpec);
    }
    if (message.toSpec !== undefined) {
      obj.toSpec = ReferenceLineSpec.toJSON(message.toSpec);
    }
    if (message.fill !== "") {
      obj.fill = message.fill;
    }
    if (message.fillOpacity !== 0) {
      obj.fillOpacity = message.fillOpacity;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReferenceBandSpec>, I>>(base?: I): ReferenceBandSpec {
    return ReferenceBandSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReferenceBandSpec>, I>>(object: I): ReferenceBandSpec {
    const message = createBaseReferenceBandSpec();
    message.axis = object.axis ?? "";
    message.fromSpec = (object.fromSpec !== undefined && object.fromSpec !== null)
      ? ReferenceLineSpec.fromPartial(object.fromSpec)
      : undefined;
    message.toSpec = (object.toSpec !== undefined && object.toSpec !== null)
      ? ReferenceLineSpec.fromPartial(object.toSpec)
      : undefined;
    message.fill = object.fill ?? "";
    message.fillOpacity = object.fillOpacity ?? 0;
    return message;
  },
};

function createBaseReferenceDistributionSpec(): ReferenceDistributionSpec {
  return { axis: "", percentiles: [], scope: "", style: "", color: "" };
}

export const ReferenceDistributionSpec: MessageFns<ReferenceDistributionSpec> = {
  fromJSON(object: any): ReferenceDistributionSpec {
    return {
      axis: isSet(object.axis) ? globalThis.String(object.axis) : "",
      percentiles: globalThis.Array.isArray(object?.percentiles)
        ? object.percentiles.map((e: any) => globalThis.Number(e))
        : [],
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      style: isSet(object.style) ? globalThis.String(object.style) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
    };
  },

  toJSON(message: ReferenceDistributionSpec): unknown {
    const obj: any = {};
    if (message.axis !== "") {
      obj.axis = message.axis;
    }
    if (message.percentiles?.length) {
      obj.percentiles = message.percentiles.map((e) => Math.round(e));
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.style !== "") {
      obj.style = message.style;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReferenceDistributionSpec>, I>>(base?: I): ReferenceDistributionSpec {
    return ReferenceDistributionSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReferenceDistributionSpec>, I>>(object: I): ReferenceDistributionSpec {
    const message = createBaseReferenceDistributionSpec();
    message.axis = object.axis ?? "";
    message.percentiles = object.percentiles?.map((e) => e) || [];
    message.scope = object.scope ?? "";
    message.style = object.style ?? "";
    message.color = object.color ?? "";
    return message;
  },
};

function createBaseTotalsSpec(): TotalsSpec {
  return { kind: "", axis: "", aggregation: "", position: "", shouldAffectTotals: false };
}

export const TotalsSpec: MessageFns<TotalsSpec> = {
  fromJSON(object: any): TotalsSpec {
    return {
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      axis: isSet(object.axis) ? globalThis.String(object.axis) : "",
      aggregation: isSet(object.aggregation) ? globalThis.String(object.aggregation) : "",
      position: isSet(object.position) ? globalThis.String(object.position) : "",
      shouldAffectTotals: isSet(object.shouldAffectTotals)
        ? globalThis.Boolean(object.shouldAffectTotals)
        : isSet(object.should_affect_totals)
        ? globalThis.Boolean(object.should_affect_totals)
        : false,
    };
  },

  toJSON(message: TotalsSpec): unknown {
    const obj: any = {};
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.axis !== "") {
      obj.axis = message.axis;
    }
    if (message.aggregation !== "") {
      obj.aggregation = message.aggregation;
    }
    if (message.position !== "") {
      obj.position = message.position;
    }
    if (message.shouldAffectTotals !== false) {
      obj.shouldAffectTotals = message.shouldAffectTotals;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TotalsSpec>, I>>(base?: I): TotalsSpec {
    return TotalsSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TotalsSpec>, I>>(object: I): TotalsSpec {
    const message = createBaseTotalsSpec();
    message.kind = object.kind ?? "";
    message.axis = object.axis ?? "";
    message.aggregation = object.aggregation ?? "";
    message.position = object.position ?? "";
    message.shouldAffectTotals = object.shouldAffectTotals ?? false;
    return message;
  },
};

function createBaseVisualSpec(): VisualSpec {
  return {
    sheetId: "",
    fields: [],
    shelves: [],
    encodings: [],
    filters: [],
    parameters: [],
    lodCalculations: [],
    markType: 0,
    analytics: undefined,
    isGenerativeAiWebAuthoring: false,
    domainType: "",
    joinLodOverrides: [],
    tableCalcSpecs: [],
  };
}

export const VisualSpec: MessageFns<VisualSpec> = {
  fromJSON(object: any): VisualSpec {
    return {
      sheetId: isSet(object.sheetId)
        ? globalThis.String(object.sheetId)
        : isSet(object.sheet_id)
        ? globalThis.String(object.sheet_id)
        : "",
      fields: globalThis.Array.isArray(object?.fields)
        ? object.fields.map((e: any) => Field.fromJSON(e))
        : [],
      shelves: globalThis.Array.isArray(object?.shelves) ? object.shelves.map((e: any) => Shelf.fromJSON(e)) : [],
      encodings: globalThis.Array.isArray(object?.encodings)
        ? object.encodings.map((e: any) => Encoding.fromJSON(e))
        : [],
      filters: globalThis.Array.isArray(object?.filters) ? object.filters.map((e: any) => FilterSpec.fromJSON(e)) : [],
      parameters: globalThis.Array.isArray(object?.parameters)
        ? object.parameters.map((e: any) => Parameter.fromJSON(e))
        : [],
      lodCalculations: globalThis.Array.isArray(object?.lodCalculations)
        ? object.lodCalculations.map((e: any) => LodCalculation.fromJSON(e))
        : globalThis.Array.isArray(object?.lod_calculations)
        ? object.lod_calculations.map((e: any) => LodCalculation.fromJSON(e))
        : [],
      markType: isSet(object.markType)
        ? markTypeFromJSON(object.markType)
        : isSet(object.mark_type)
        ? markTypeFromJSON(object.mark_type)
        : 0,
      analytics: isSet(object.analytics) ? Analytics.fromJSON(object.analytics) : undefined,
      isGenerativeAiWebAuthoring: isSet(object.isGenerativeAiWebAuthoring)
        ? globalThis.Boolean(object.isGenerativeAiWebAuthoring)
        : isSet(object.is_generative_ai_web_authoring)
        ? globalThis.Boolean(object.is_generative_ai_web_authoring)
        : false,
      domainType: isSet(object.domainType)
        ? globalThis.String(object.domainType)
        : isSet(object.domain_type)
        ? globalThis.String(object.domain_type)
        : "",
      joinLodOverrides: globalThis.Array.isArray(object?.joinLodOverrides)
        ? object.joinLodOverrides.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.join_lod_overrides)
        ? object.join_lod_overrides.map((e: any) => globalThis.String(e))
        : [],
      tableCalcSpecs: globalThis.Array.isArray(object?.tableCalcSpecs)
        ? object.tableCalcSpecs.map((e: any) => TableCalcSpec.fromJSON(e))
        : globalThis.Array.isArray(object?.table_calc_specs)
        ? object.table_calc_specs.map((e: any) => TableCalcSpec.fromJSON(e))
        : [],
    };
  },

  toJSON(message: VisualSpec): unknown {
    const obj: any = {};
    if (message.sheetId !== "") {
      obj.sheetId = message.sheetId;
    }
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => Field.toJSON(e));
    }
    if (message.shelves?.length) {
      obj.shelves = message.shelves.map((e) => Shelf.toJSON(e));
    }
    if (message.encodings?.length) {
      obj.encodings = message.encodings.map((e) => Encoding.toJSON(e));
    }
    if (message.filters?.length) {
      obj.filters = message.filters.map((e) => FilterSpec.toJSON(e));
    }
    if (message.parameters?.length) {
      obj.parameters = message.parameters.map((e) => Parameter.toJSON(e));
    }
    if (message.lodCalculations?.length) {
      obj.lodCalculations = message.lodCalculations.map((e) => LodCalculation.toJSON(e));
    }
    if (message.markType !== 0) {
      obj.markType = markTypeToJSON(message.markType);
    }
    if (message.analytics !== undefined) {
      obj.analytics = Analytics.toJSON(message.analytics);
    }
    if (message.isGenerativeAiWebAuthoring !== false) {
      obj.isGenerativeAiWebAuthoring = message.isGenerativeAiWebAuthoring;
    }
    if (message.domainType !== "") {
      obj.domainType = message.domainType;
    }
    if (message.joinLodOverrides?.length) {
      obj.joinLodOverrides = message.joinLodOverrides;
    }
    if (message.tableCalcSpecs?.length) {
      obj.tableCalcSpecs = message.tableCalcSpecs.map((e) => TableCalcSpec.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisualSpec>, I>>(base?: I): VisualSpec {
    return VisualSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisualSpec>, I>>(object: I): VisualSpec {
    const message = createBaseVisualSpec();
    message.sheetId = object.sheetId ?? "";
    message.fields = object.fields?.map((e) => Field.fromPartial(e)) || [];
    message.shelves = object.shelves?.map((e) => Shelf.fromPartial(e)) || [];
    message.encodings = object.encodings?.map((e) => Encoding.fromPartial(e)) || [];
    message.filters = object.filters?.map((e) => FilterSpec.fromPartial(e)) || [];
    message.parameters = object.parameters?.map((e) => Parameter.fromPartial(e)) || [];
    message.lodCalculations = object.lodCalculations?.map((e) => LodCalculation.fromPartial(e)) || [];
    message.markType = object.markType ?? 0;
    message.analytics = (object.analytics !== undefined && object.analytics !== null)
      ? Analytics.fromPartial(object.analytics)
      : undefined;
    message.isGenerativeAiWebAuthoring = object.isGenerativeAiWebAuthoring ?? false;
    message.domainType = object.domainType ?? "";
    message.joinLodOverrides = object.joinLodOverrides?.map((e) => e) || [];
    message.tableCalcSpecs = object.tableCalcSpecs?.map((e) => TableCalcSpec.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
