"""BaseDialect — visitor that walks SQLQueryFunction and calls format_*
hooks. Dialect-specific subclasses live in backend/vizql/dialects/.

Mirrors Tableau's BaseDialect / SQLDialect (Build_Tableau.md §IV.5).
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional

from . import sql_ast as sa


class BaseDialect(ABC):
    """Abstract dialect. Override format_* methods in subclasses."""

    name: str = "base"

    # ---- Top-level entry (Task 2 fills this in) ----
    def emit(self, qf: sa.SQLQueryFunction) -> str:
        raise NotImplementedError("BaseDialect.emit is implemented in Task 2")

    # ---- §IV.5 format catalogue — abstract on the base, overridable per dialect ----
    @abstractmethod
    def format_select(self, qf: sa.SQLQueryFunction) -> str: ...
    @abstractmethod
    def format_join(self, j: sa.JoinNode) -> str: ...
    @abstractmethod
    def format_case(self, c: sa.Case) -> str: ...
    @abstractmethod
    def format_simple_case(self, c: sa.Case) -> str: ...
    @abstractmethod
    def format_aggregate(self, f: sa.FnCall) -> str: ...
    @abstractmethod
    def format_window(self, w: sa.Window) -> str: ...
    @abstractmethod
    def format_cast(self, c: sa.Cast) -> str: ...
    @abstractmethod
    def format_drop_column(self, table: str, column: str) -> str: ...
    @abstractmethod
    def format_table_dee(self) -> str: ...
    @abstractmethod
    def format_default_from_clause(self) -> str: ...
    @abstractmethod
    def format_set_isolation_level(self, level: str) -> str: ...
    @abstractmethod
    def format_boolean_attribute(self, v: bool) -> str: ...
    @abstractmethod
    def format_float_attribute(self, v: float) -> str: ...
    @abstractmethod
    def format_integer_attribute(self, v: int) -> str: ...
    @abstractmethod
    def format_int64_attribute(self, v: int) -> str: ...
    @abstractmethod
    def format_top_clause(self, n: int) -> str: ...
    @abstractmethod
    def format_offset_clause(self, n: int) -> str: ...
    @abstractmethod
    def format_string_literal(self, v: str) -> str: ...
    @abstractmethod
    def format_identifier(self, ident: str) -> str: ...
    @abstractmethod
    def format_date_trunc(self, part: str, expr: str) -> str: ...
    @abstractmethod
    def format_datediff(self, part: str, a: str, b: str) -> str: ...
    @abstractmethod
    def format_extract(self, part: str, expr: str) -> str: ...
    @abstractmethod
    def format_current_timestamp(self) -> str: ...
    @abstractmethod
    def format_interval(self, part: str, n: int) -> str: ...


__all__ = ["BaseDialect"]
