/**
 * Result shape analyzer — inspects a query result's column profile and
 * produces a summary used by the Show Me recommender to pick chart types.
 *
 * Spec source of truth:
 * docs/superpowers/specs/2026-04-15-chart-system-sub-project-a-design.md §11.4
 *
 * Reference:
 * docs/chart_systems_research.md §2.2 (Mackinlay-Hanrahan-Stolte rules)
 */
import type { SemanticType } from '../types';

/** Threshold for "high cardinality" — used to decide bar vs treemap, etc. */
export const HIGH_CARDINALITY_THRESHOLD = 20;

/**
 * Profile of a single result-set column. Generated by the backend
 * column profiler in query_engine.py and shipped in the query response.
 */
export interface ColumnProfile {
  name: string;
  dtype: 'int' | 'float' | 'string' | 'date' | 'bool' | 'geo';
  role: 'dimension' | 'measure';
  semanticType: SemanticType;
  cardinality: number;
  nullPct: number;
  sampleValues: unknown[];
}

/** Input to the analyzer. */
export interface ResultShapeInput {
  columns: ColumnProfile[];
  rowCount: number;
}

/**
 * Output of the analyzer. Used by the Show Me recommender to filter
 * which chart types are valid for the given data shape.
 */
export interface ResultShape {
  /** Original column profiles (for downstream rule access). */
  columns: ColumnProfile[];
  /** Number of dimension columns. */
  nDimensions: number;
  /** Number of measure columns. */
  nMeasures: number;
  /** True if at least one dimension is temporal. */
  hasDate: boolean;
  /** True if at least one dimension is geographic. */
  hasGeo: boolean;
  /** Maximum cardinality across all dimension columns. */
  maxDimensionCardinality: number;
  /** True if any dimension cardinality > HIGH_CARDINALITY_THRESHOLD. */
  hasHighCardinalityDim: boolean;
  /** Total row count of the result set. */
  rowCount: number;
}

/**
 * Inspect a result set's column profile and produce a shape summary.
 * Pure function — no side effects.
 */
export function analyzeResultShape(input: ResultShapeInput): ResultShape {
  const dimensions = input.columns.filter((c) => c.role === 'dimension');
  const measures = input.columns.filter((c) => c.role === 'measure');

  const maxDimCard = dimensions.length > 0
    ? Math.max(...dimensions.map((d) => d.cardinality))
    : 0;

  return {
    columns: input.columns,
    nDimensions: dimensions.length,
    nMeasures: measures.length,
    hasDate: dimensions.some((d) => d.semanticType === 'temporal'),
    hasGeo: dimensions.some((d) => d.semanticType === 'geographic'),
    maxDimensionCardinality: maxDimCard,
    hasHighCardinalityDim: maxDimCard > HIGH_CARDINALITY_THRESHOLD,
    rowCount: input.rowCount,
  };
}
